# Imports

# New Section

In [ ]:
import pandas as pd

# Data Structures

In [ ]:
# tuple: tuple is a fixed length
tup = (4, 5, 6, 7, 8)

tup

(4, 5, 6, 7, 8)

In [ ]:
tuple ([4, 5, 6, 7])


(4, 5, 6, 7)

In [ ]:
tup = tuple ('Samuel')
tup


('S', 'a', 'm', 'u', 'e', 'l')

In [ ]:
tup[2:5]

('m', 'u', 'e')

In [ ]:
tup[1:4]

('a', 'm', 'u')

In [ ]:
tup = tuple(['life', [a, b], True])
tup[2] = False

NameError: name 'a' is not defined

In [ ]:
# lists
ls = ["this", "is", "Africa"]

In [ ]:
seq = [1, 2, 3, 4, 5, 6, 9, 7, 8, 9]
seq [1:5]

[2, 3, 4, 5]

In [ ]:
empty_dict = {}
d1 = {"a": "Samuel", "b": [0,7,5,6]}
d1

{'a': 'Samuel', 'b': [0, 7, 5, 6]}

In [ ]:
tup = (2, 5, 6)
d2 = {tup: "phone num", [0, 7, 5, 6]: "b"   }
d2

TypeError: unhashable type: 'list'

In [ ]:
list = [a, b, c, d, e]

In [ ]:
mapping = {}
for key, value in zip(key_list, value_list):
  mapping[key] = value

NameError: name 'key_list' is not defined

In [ ]:
tuples = zip(range(5), reversed(range(5)))
tuples

In [ ]:
mapping = dict(tuples)
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

# Functions

In [ ]:
# Functions
def myfunc (a, b):
  return a/b

In [ ]:
myfunc(4, 3)

1.3333333333333333

# Numpy

In [ ]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

my_arr


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
#create a list of lists
List = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
List

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
np.array(List)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
data = np.array(List)
data + data


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
data * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [ ]:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
#Shapes
data = np.array(List)
data.shape

(3, 4)

In [ ]:
data.dtype

dtype('int64')

# ndArrays

In [ ]:
data2 = [2.0, 3.1, 3.5, 5, 7]
data2 = np.array(data2)
data2

array([2. , 3.1, 3.5, 5. , 7. ])

# Arithmetic with NumPy Arrays

In [ ]:
arry = np.array([[1, 2, 3], [4, 5, 6]])
arry

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arry * arry

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arry - arry

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
1/ arry

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arry **3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [ ]:
arry = np.arange(10)
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arry[6]

6

In [ ]:
arry[5:8]

array([5, 6, 7])

In [ ]:
arry[5:8] = 13
arry

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [ ]:
#boolean Indexing
names = np.array([1, 2, 3, 4, 5, 6, 7, 8])
data = np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])
names

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
data == 2

array([[False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False]])

In [36]:
names == 2

array([False,  True, False, False, False, False, False, False])